### ISSUE TITLE
Incluir data da última atualização

### ISSUE THREAD

**Issue by resendedaniel** [resendedaniel/covid#1]
O dia com último dado é possível extrair dos dados, é a maior data disponível.

Talvez seja possível estimular a percepção do usuário mexendo no eixo x do gráfico.
Considere experimentar colocar no eixo x somente janeiro e dezembro fixos e o dia com o último dado disponível.

Talvez também Colocar uma linha vertical tracejada na data de hoje pra indicar o lag dos dados.

De qualquer maneira, está no texto explicações do atraso dos cartórios.

**Comment by chamun** [comment]
> O dia com último dado é possível extrair dos dados, é a maior data disponível.

Acho que não podemos usar a maior data disponivel dos dados pois ela não é necessariamente a data de atualização. Lembra que estamos cortando os últimos 15 dias, então se eu atualizasse os dados hoje, a última data disponível seria 20 de maio, mas a data de atualização deveria ser hoje.

Essa informação pode estar incluída no JSON e ser preenchida quando o script roda. Dessa maneira a gente pode ter inclusive a hora em que os dados foram atualizados.

Propnho atualizar o JSON para algo assim:

```js
{
  lastUpdate: '2020-06-03T023:00:00Z', /* timestamp em UTC */
  dataPoints: [ /* o conteúdo atual do JSON */ ]
}
```

**Comment by resendedaniel** [comment]
Ok, vou trabalhar nisso. Acho que posso colocar outras coisas úteis também. Tipo o número de mortes total, número de mortes excedentes, percentual de acréscimo.

**Comment by resendedaniel** [comment]
Criei esse novo formato de data. Está assim:
{
    "last_date": "2020-05-23T00:00:00",
    "updated_date": "2020-06-06T12:17:51.727993",
    "data": []
}

Coloquei em outra branch "new-data-format" por que não consegui arrumar o js pra pegar os dados nesse formato.

Aproveitei e criei duas colunas novas, excess e cum_excess que mostra o excesso de mortes no dia (2020 - 2019) e o valor acumulado disso. Dá pra fazer um outro gráfico disso dps.

**Comment by chamun** [comment]
Vou atulizar o JS no branch `new-data-format`.

**Comment by chamun** [comment]
Acabei não usando o `last_date`, pode tirar ele.
