### ISSUE TITLE
Rodapé com contato

### ISSUE THREAD

**Issue by resendedaniel** [resendedaniel/covid#13]
Acho que seria legal colocar algum contato no site, sempre tem gente interessante que quer falar algo. Tem mais gente querendo xingar, mas só ignorar essa galera.

Nem que seja um contato do Twitter pra ser mais simplão.

O que acha? Gostaria de colocar o seu contato tbm?

**Comment by chamun** [comment]
Acho uma boa ideia, vi que tu já colocou o teu contato.

Depois eu atualizo o código com o meu contato também.

**Comment by resendedaniel** [comment]
Pensei em colocar uma coisa assim, talvez em duas colunas:

Criadores e desenvolvedores:
Daniel Resende
Rodrigo Chamun

Redatora e assessoria de comunicação
Isabella Paschuini
Bruno Aragaki

Assessoria Técnica
MArcelo Oliveira
Thomas Fujiwara
Otavio Ranzani

Outras fontes
NYT
FT
