### ISSUE TITLE
Route parameters

### ISSUE THREAD

**Issue by resendedaniel** [resendedaniel/covid#14]
Seria legal ter caminhos na url, tipo /sp /rs /am pra levar direto para a página do estado.

Estou colocando só por que me veio a cabeça, não precisa fazer não.

**Comment by chamun** [comment]
Acho uma ótima ideia!

**Comment by resendedaniel** [comment]
Outra coisa. Acho que dá pra pensar em um caminho duplo, tipo /sp/all, /sp/campinas, /rs/porto-alegre. Pois temos esses dados em nível de município.

Eu posso fazer o corre de trazer os dados nesse nível.

**Comment by chamun** [comment]
Referencias:

- Manipular histórico: https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API
- SPA no GithubPages: https://medium.com/swlh/how-to-host-your-angular-reactjs-vuejs-spa-on-github-pages-2d9ab102ac7b
- Analytics: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
- Roteador vanilla: https://github.com/krasimir/navigo, https://www.npmjs.com/package/vanilla-router

**Comment by chamun** [comment]
> Outra coisa. Acho que dá pra pensar em um caminho duplo, tipo /sp/all, /sp/campinas, /rs/porto-alegre. Pois temos esses dados em nível de município.

Acho que dá pra aproveitar a estrutura de diretórios pra implementar essa granularidade:

```
+ data/
|-- all.json
|-+ estado_01/
  |-- all.json
  |-- cidade_01.json
  |-- cidade_02.json
```

E no JSON ter alguma coisa assim:
```
{
  state: 'estado_01',
  cities: ['all', '01', '02'],
}
```

**Comment by chamun** [comment]
- Vercel | SPA Fallback: https://vercel.com/docs/configuration?query=single%20page%20application#routes/advanced/spa-fallback
