### ISSUE TITLE
Enriquecimento de dados no front

### ISSUE THREAD

**Issue by resendedaniel** [resendedaniel/covid#5]
Não sei quão simples é isso e nem se faz sentido, mas fiquei pensando e divagando na estrutura de dados mais leve.

O mínimo que deveria trafegar é data e número de mortes no dia, talvez o label do local.
Com data da pra extrair o ord_d e o ano.
O local daria pra pegar do nome do arquivo, mas parece ser um dado primário e deveria andar junto com o dado, além disso é bem compressível.

O cálculo da média móvel poderia também ser feito no front. Isso permitiria enriquecer um pouco a visualização. Tipo, quando passar o mouse sobre a linha de um ano, mostrar umas bolinhas com o valor real. Ajuda a intuir o funcionamento e não complica muito de cara.

Estou viajando um pouco aqui, não precisamos ser ultra eficientes.

**Comment by chamun** [comment]
Gostei das duas ideias, mas não acho que não é prioridade para a primeira release.
