### ISSUE TITLE
Domínio

### ISSUE THREAD

**Issue by resendedaniel** [resendedaniel/covid#8]
Podemos pensar em um domínio. Dá pra criar uma organização no github e transferir o repositório pra lá, daí seguimos com o github pages.

Ou podemos ir direto pra um domínio mesmo.

**Comment by chamun** [comment]
Qualquer opção tá legal pra mim.

A vantagem do domínio é poder trocar a hospedagem da página sem se preocupar em redirecionar o usuário, também é uma maneira de dar uma identidade mais forte para o projeto.

**Comment by resendedaniel** [comment]
Pois é, estou pensando bastante nisso. Mas não consigo chegar em nada.

Poderia ser um domínio mais específico de Covid e um projeto mais fechado em si mesmo. Ou poderia ser algo mais amplo que permitisse outros estudos inclusive de outros temas.

Eu tive esse problema com o Comparação de Fundos. A gente tinha um domínio muito específico, porém quando a gente foi fazer uma robo advisor, a gente extrapolava fundos e o domínio ficava muito restritivo. Daí criamos o Vérios que era mais abrangente.

**Comment by resendedaniel** [comment]
Que acha de monitordemortes.com.br? Muito creep?

**Comment by resendedaniel** [comment]
mortalidade.com.br tá disponível tbm

**Comment by chamun** [comment]
No começo achei mortalidade.com.br mórbido, mas acho que é facil de lembrar e é abrangente o suficiente pra incluir outros indices de mortalidade relacionados à COVID-19.

Nós poderiamos monitorar mortes por doenças cardiovasculares, "em casa" e causa não informada também.

**Comment by resendedaniel** [comment]
Tbm achei morbido, mas uma palavra do dicionário disponível não se acha todo dia.

Acho que dá pra crescer mesmo nas causas. Tem uma outra base mensal mais ampla.

Vou fechar essa issue por ora.
